name: Build and Deploy
on:
  push:
    branches:
    - master
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Build
      uses: docker://node:10.16.3
      with:
        args: run build
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.3
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: monopoly-wallet-b2102
        TARGET_BRANCH: master